apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms-db
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rooms-db
  template:
    metadata:
      labels:
        app: rooms-db
    spec:
      containers:
        - name: rooms-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "rooms"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rooms-db-pvc
