apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: chat-app/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION_MS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_EXPIRATION_MS
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_SERVICE_URL
            - name: ROOM_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ROOM_SERVICE_URL
            - name: CHAT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CHAT_SERVICE_URL
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
