apiVersion: v1
kind: Service
metadata:
  name: moderation-service
  namespace: chat-app
spec:
  type: LoadBalancer
  selector:
    app: moderation-service
  ports:
    - port: 8000
      targetPort: 8000
