apiVersion: v1
kind: Service
metadata:
  name: room-service
  namespace: chat-app
  labels:
    app: room-service
spec:
  selector:
    app: room-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
