apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: room-service
          image: chat-app/room-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ROOMS_DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
